version: 2

jobs:
  development:
    docker:
      - image: circleci/python:3.7.2

    steps:
      - checkout
      - run:
          name: Install
          command: |
            poetry install
      - run:
          name: Test
          command: |
            poetry run tox

workflows:
  version: 2

  development-workflow:
    jobs:
      - development


