version: 2

jobs:
  development:
    docker:
      - image: circleci/python:3.7.2

    steps:
      - checkout
      - run:
          name: Install
          command: |
            poetry install
      - run:
         name: Lint
         command: |
            poetry run flake8 {{ cookiecutter.app_name }}
      - run:
          name: Test
          command: |
            poetry run tox
      - run:
          name: Documentation
          command: |
            poetry run sphinx-apidoc -o docs/ {{ cookiecutter.app_name }} --force
      - run:
         name: Report
         command: |
            poetry run codecov

  deployment:
      docker:
        - image: circleci/python:3.7.2

      steps:
        - checkout
        - run:
            name: Publish
            command: |
              poetry publish --build --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction

workflows:
  version: 2

  development-workflow:
    jobs:
      - development

  deployment-workflow:
    jobs:
      - development:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - deployment:
          requires:
            - development
          filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*/
              branches:
                ignore: /.*/

